// Auto-generated by fix-supabase-import.ps1
// Re-exports the single supabase instance so legacy imports resolve.
import { supabase } from '../../lib/supabase';

export { supabase };

export async function isAuthenticated() {
  const { data: { session } } = await supabase.auth.getSession();
  return !!session;
}

export async function getCurrentUser() {
  const { data: { session } } = await supabase.auth.getSession();
  return session?.user || null;
}
